name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Sync from GitLab"]
    types:
      - completed

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: Prepare
        run: |
            platform=${{ matrix.platform }}
            echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/$PLATFORM_PAIR:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Save Docker image as tar.xz
        run: docker save ghcr.io/${{ github.repository_owner }}/$PLATFORM_PAIR:latest > webtunnel_$PLATFORM_PAIR.tar && xz -kv9T0 webtunnel_$PLATFORM_PAIR.tar && echo "FILENAME=webtunnel_$PLATFORM_PAIR.tar.xz" >>$GITHUB_ENV

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
          compression-level: 0
