name: Sync from GitLab

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    -
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: Clone GitLab repository
      run: |
        git clone https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel.git gitlab_repo
        cp -r gitlab_repo/* ./

    - name: Check for changes
      run: |
        rm -rf gitlab_repo/
        cat README.txt | sed -i '1iThis repository was cloned from [gitlab.torproject.org](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel).This is NOT official project.DO NOT seek supprt to Tor Project Forum about issues of the docker images. Some files were modified by [GitHub Actions script](https://github.com/misakazip/Tor-WebTunnel-Docker/blob/main/.github/workflows/sync_from_gitlab.yml).' README.md
        sed -i s@thetorproject/webtunnel-bridge:latest@ghcr.io/misakazip/tor-webtunnel:latest@g release/container/docker-compose.yml
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Sync from GitLab repository"
          git push
        fi
