name: Sync from GitLab

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone GitLab repository
      run: |
        git clone https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel.git gitlab_repo
        cp -r gitlab_repo/* ./

    - name: Check for changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Sync from GitLab repository"
          git push
        fi
